package hub
package main

















































}	}		log.Fatalf("Server error: %v", err)	if err := server.ListenAndServe(); err != http.ErrServerClosed {	log.Printf("Santoki Hub starting on %s", cfg.ServerAddr)	}()		}			log.Printf("Server shutdown error: %v", err)		if err := server.Shutdown(ctx); err != nil {		defer cancel()		ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)		<-sigChan		signal.Notify(sigChan, syscall.SIGINT, syscall.SIGTERM)		sigChan := make(chan os.Signal, 1)	go func() {	// Graceful shutdown	}		IdleTimeout:  60 * time.Second,		WriteTimeout: 15 * time.Second,		ReadTimeout:  15 * time.Second,		Handler:      router,		Addr:         cfg.ServerAddr,	server := &http.Server{	router := api.NewRouter(cfg)	}		log.Fatalf("Failed to load config: %v", err)	if err != nil {	cfg, err := config.Load()func main() {)	"github.com/cookieshake/santoki/packages/hub/internal/config"	"github.com/cookieshake/santoki/packages/hub/api"	"time"	"syscall"	"os/signal"	"os"	"net/http"	"log"	"context"import (