// This file is auto-generated by Santokit CLI.
// Do not edit manually.

import '@santokit/client';

declare module '@santokit/client' {
  interface LogicNamespace {
    cache: {
      ping: (params: {
      }) => Promise<any>;
    };
    echo: {
      ping: (params: {
        message: string;
      }) => Promise<any>;
    };
    storage: {
      delete: (params: {
      }) => Promise<any>;
      presign: (params: {
      }) => Promise<any>;
    };
  }
}
